### ISSUE TITLE
Recommended hardware setup

### ISSUE THREAD

**Issue by khssnv** [tardis-dev/serum-vial#13]
Hi! At first, thank you for the awesome project! I'm testing it for a week now and I see it's all stable, but the CPU load average differs from 16 to 100+ day to day for my setup process 140+ Serum markets. Do you have any recommendations about hardware setup? Thanks!

**Comment by thaaddeus** [comment]
Hi, I'm running currently on AMD AMD Ryzen 7 3700X and it has a lot of headroom, but don't have any minimum hardware setup requirements, for sure it's rather bandwidth hungry due to Serum event queue accounts notification size (each notification is ~1MB)
