### ISSUE TITLE
Basic HTTP Auth

### ISSUE THREAD

**Issue by khssnv** [tardis-dev/serum-vial#15]
Hello. Can I connect to Solana RPC with basic HTTP Auth specifying login in a password in `endpoint` argument like `https://login:password@example.com`?

**Comment by thaaddeus** [comment]
I'm not sure, you can try but I've never tested that scenario, pull requests are welcome.

**Comment by khssnv** [comment]
Ok, thanks!

**Comment by khssnv** [comment]
I made an experiment and I see it works. One may specify an endpoint with credentials in URL like `https://login:password@example.com` and Serum Vial requests will pass authentication.
