### ISSUE TITLE
WebSocket connection warnings

### ISSUE THREAD

**Issue by khssnv** [tardis-dev/serum-vial#16]
Hello. I have the latest dockerized Serum Vial running on a 6 CPU and 16Gb RAM machine that works with a dedicated Solana RPC node querying for 143 markets data. There is a lot of WebSocket connection warning messages as mentioned below. I see they usually appear in 5-10 minutes after an instance starts. Is it a problem and what side I should tune to fix it (Solana RPC, Serum Vial, or connectivity between them)? Let me know if the full log may help. Thank you!

```console
warn: WS send error: write ECONNRESET
warn: WS send error: write EPIPE
warn: WS send error: WebSocket is not open: readyState 2
warn: WS send error: WebSocket is not open: readyState 3 (CLOSED)
warn: Out of order notification for PUBLISHED event: current slot 77095564, update slot: 77095564, resetting... {"market":"SRM/SOL"}
```

**Comment by thaaddeus** [comment]
Hi, I had issues running on smaller machines as Solana RPC requires quite a lot of resources (memory as well) - right now I'm running on https://www.hetzner.com/dedicated-rootserver/ax101 (AMD Ryzen™ 9 5950X 16-Core, 128GB of RAM) and it's very stable.
WS send logs can be ignored I think (it's client that connects to serum-vial dropped connection)
Out of order notification could suggest you're running out of resources, what's your CPU usage?

**Comment by khssnv** [comment]
Thank you for sharing your experience!
In my deployment, Solana RPC and Serum Vial work on different machines.

Serum Vial instance leaves half of the CPU time for idle.
![image](https://user-images.githubusercontent.com/833019/117445496-ca842d00-af4b-11eb-9fb7-13212c677c2a.png)

But load average is very high for a 6 CPU machine by the way :thinking:
![image](https://user-images.githubusercontent.com/833019/117445572-e5ef3800-af4b-11eb-9475-6476eaf3ccde.png)

**Comment by thaaddeus** [comment]
I see, thanks. Well the main reason why it is cpu time consuming on serum-vial side is that `eventQueue` account change notifications are quite large in size (>1MB) so if you subscribe to >140 markets and let's say each market notifies twice a second about it's eventQueue account change, then it's a quite a lot of data to even receive and parse.
What I can share is that with setup mentioned above I got no warnings for last few days.

**Comment by khssnv** [comment]
Thank you for your clarification. What machine you think is OK for such a Serum Vial instance processing 143 markets (without Solana node on the same host)? Also, do you think it's a good idea to keep one Serum Vial instance processing 143 markets or I better run one instance per for 20-30 markets if it makes any difference?

**Comment by thaaddeus** [comment]
I'm not sure, I'd think your machine size should be good enough, but if you'd see a lot 'out of order' warnings then it could be that your RPC node or serum-vial are lagging but it's hard to know which one, in my case it was always RPC node issue.

**Comment by khssnv** [comment]
Thank you for these clarifications :+1:
