### ISSUE TITLE
BroadcastChannel is not a constructor

### ISSUE THREAD

**Issue by ntegrals** [tardis-dev/serum-vial#20]
I am currently trying to set up Serum Vial with my own Solana Validator, and I am getting this error:

/home/linuxbrew/.linuxbrew/lib/node_modules/serum-vial/dist/helpers.js:84
exports.minionReadyChannel = new BroadcastChannel('MinionReady');
                             ^

TypeError: BroadcastChannel is not a constructor

How can I fix this?

**Comment by thaaddeus** [comment]
Hi, I think you need to use Node.js v15 which has support for BroadcastChannel

**Comment by ntegrals** [comment]
Thanks, that solved it!
