### ISSUE TITLE
is there a way to filter my orders?

### ISSUE THREAD

**Issue by Gsuz** [tardis-dev/serum-vial#26]
I'm trying to filter level3 messages which involve orders from my wallet. I thought I would be able to use the account.property but it seems that the account string is not permanently linked to the wallet and get's re-issued periodically. Is there any other way to identify the owner of the bid/ask?

**Comment by Gsuz** [comment]
should Client Id be used for this? Client Id is always 0 for me on all messages.

**Comment by thaaddeus** [comment]
Hi,

- `clientId` is a client provided order id for an order

- `account` is an open orders account address

If I remember correctly for each market you trade, there's separate open order account to your main account.
In L3 data you get open orders account not your main account.

**Comment by Gsuz** [comment]
But clientId is always zero for me in every message. A bug?

**Comment by thaaddeus** [comment]
it means it's not set by the client when sending order to the Solana RPC node, it's optional.

**Comment by Gsuz** [comment]
hmm. I'm using serum-js to send my orders. I should be able to enable it there then?

**Comment by thaaddeus** [comment]
I think so, https://github.com/project-serum/serum-ts/blob/3e6545c4338bdb66cf550f20676aab2ac8151ebd/packages/serum/src/market.ts#L429 (there's clientId in place order fn)

**Comment by Gsuz** [comment]
True. Thanks so much for your help and for looking into this.
