### ISSUE TITLE
Partial Fills w/ Cancellation & Immediate Maker Fills

### ISSUE THREAD

**Issue by chris-rr** [tardis-dev/serum-vial#31]
Hi @thaaddeus, a couple of other possible issues in the message progression which have been encountered:

1. Quite regularly observe situation where an order is opened, `fill` messages are received for a _part_ of the order size, and then a `done` message with `reason=filled` is received - suspect that these are orders which are partially filled and then cancelled, and so should be flagged as `reason=canceled`?

2. There are also regular cases where a `fill` message is received with `maker=true`, but no `open` message for the order has previously been generated.  I expect that here the order is opened and immediately filled in full or in part on the same update; I would expect this scenario to produce both an `open` and a `fill` for the order (since it doesn't make sense to have a `maker` fill for an order that hasn't been opened on the book).

Let me know if you need any other info.
Thanks!

**Comment by thaaddeus** [comment]
re 1.: I think it can be detected and improved, will provide a fix soon.
re 2.: I could not reproduce it (checked last two weeks of data), could it be that you have unstable connection to Solana RPC node?

**Comment by chris-rr** [comment]
1. Awesome, thanks!
2. Hmm, will take another look at this, perhaps there is another explanation.

**Comment by thaaddeus** [comment]
@chris-rr please try v1.3.0 it should have both issues fixed (also now done (canceled) orders have sizeRemaining and price fields). I did not have bunch of time to test it, so please keep that in mind and revert to v1.2.x if needed.

**Comment by tadeuszwojcik** [comment]
seems like v1.3.0 has a bug that makes it unstable, please keep using v1.2.10 for now.

**Comment by thaaddeus** [comment]
v1.3.1 should be stable (but I had to revert some changes, no price or sizeRemaining for done(cancel) messages for now).

**Comment by chris-rr** [comment]
Thanks for this @thaaddeus, can confirm no further occurrences of these issues over a day of data collected using the latest (1.3.2) version 👍  Will let you know if finding any other inconsistencies during further tests.

**Comment by thaaddeus** [comment]
That's great, you may also want to update to the latest version, it has few more tweaks & small improvements.
