### ISSUE TITLE
1.3.0 broken

### ISSUE THREAD

**Issue by yamen** [tardis-dev/serum-vial#32]
I did read you had limited time to test, but 1.3.0 seems to be broken for level3 messages.

The simplest possible test:

- Run latest `serum-vial`
- Connect using `websocat` or similar and send `{"op":"subscribe","channel":"level3","markets":["SOL/USDC"]}`

Expected:

- Receive l3snapshot
- Receive subscribed
- Start receiving open / fill / done etc messages

Actual:

- Receive l3snapshot and subscribed, but no open / fill / done etc messages

Reverting to 1.2.10 and it works.

**Comment by thaaddeus** [comment]
@yamen I'm looking into that, please keep using v1.2.10 for now.

**Comment by thaaddeus** [comment]
v1.3.1 should be stable (but I had to revert some changes, no price or sizeRemaining for done(cancel) messages for now).
