### ISSUE TITLE
Unhandled exception in serum producer worker

### ISSUE THREAD

**Issue by bravehearto0** [tardis-dev/serum-vial#34]
Since yesterday met the following exceptions:

2021-11-24T20:24:32.564Z error: Serum producer worker 10 error occurred: The user aborted a request. undefined
Uncaught Exception thrown { type: 'aborted', message: 'The user aborted a request.' }

take a look at market, it seems that each time it is a different market. looks like the error is from client side.

**Comment by thaaddeus** [comment]
The only scenario I can think of when this error could manifest is when Solan RPC nodes you're using did not return any data after 10 retries. Do you use your own RPC node or serum public one?

**Comment by thaaddeus** [comment]
Please reopen if you'll have more details regarding the issue.
