### ISSUE TITLE
Frequent socket termination

### ISSUE THREAD

**Issue by Vaulverin** [tardis-dev/serum-vial#35]
There is an issue with frequent socket termination from this if condition 
https://github.com/tardis-dev/serum-vial/blob/master/src/rpc_client.ts#L257

I've found out that a response to "ping" message is `error: { code: -32601, message: 'Method not found' }` and when we receive it in the condition above we terminate Socket connection, but it's not necessary - because nothing went wrong.

**Comment by thaaddeus** [comment]
Can you share which version of Solan RPC node you're using? I'm running one with internal RPC node (1.8.5) and one that connects to public Serum RPC nodes pool and both never return 'error' for ping request.

**Comment by Vaulverin** [comment]
I'm using dedicated node provided by this service https://www.quicknode.com/.
The version is 1.8.5 too.
I haven't tried it on public nodes though.

**Comment by thaaddeus** [comment]
This is from Mango RPC nodes - they also sending pings - those prevent connection to close on inactivity
<img width="567" alt="image" src="https://user-images.githubusercontent.com/51779538/145413077-af67a4b5-7ade-43bd-96d7-8cd990b9b3b9.png">

**Comment by thaaddeus** [comment]
could it be that quicknode somehow disabled that method?

**Comment by Vaulverin** [comment]
hm is it possible?
i'll ask their support

**Comment by thaaddeus** [comment]
not sure, I can only say that never had an issue you've mentioned (error response).
Best to confirm with their support.

**Comment by Gsuz** [comment]
I'm getting this error as well. Did you confirm this with quicknode support? @Vaulverin

**Comment by Vaulverin** [comment]
I don't remember if I confirmed it with quicknode support. As far as i remember I just patched the code to handle this error without connection termination.
