### ISSUE TITLE
Execution ID

### ISSUE THREAD

**Issue by quazzuk** [tardis-dev/serum-vial#36]
Hi

I was just wondering whether there is something equivalent to an execution identifier for fills on Serum? I assume it's possible to get partial fills (?) so the order_id wouldn't be unique and also could receive multiple partials with the same timestamp (?) Perhaps there is a suitable alternative SHA256(blockhash, offset)?

Thanks
Andrew

**Comment by thaaddeus** [comment]
Unfortunately, I don't know if such thing exist, but if you'll find anything please let me know.
