### ISSUE TITLE
Trade Id

### ISSUE THREAD

**Issue by quazzuk** [tardis-dev/serum-vial#44]
Hi

qq - I'm in the situation where I need both a `tradeId` field and fee information on trade events but there doesn't appear to be a message with contains both. Is there anything the prevents the L3 `fill` event having the `tradeId` or L2 `trade` event having fee information?

Thanks

**Comment by thaaddeus** [comment]
Trade is is simply concatenated taker and maker order ids of fills (https://github.com/tardis-dev/serum-vial/blob/master/src/data_mapper.ts#L362) so I guess you can use that to get matching fills info.

**Comment by quazzuk** [comment]
Would this require "joining" the taker and maker fill events? Is it possible to add this info before sending?

**Comment by thaaddeus** [comment]
It should just require finding matching fill events with trade by maker and taker ids, there are no plans currently to extend trade message with additional info, that's why fill events are available as well and can be used as an alternative to trade messages if needed.
