### ISSUE TITLE
--markets-json option has no effect

### ISSUE THREAD

**Issue by yuduan0220** [tardis-dev/serum-vial#48]
Hi, I'm trying to use --markets-json with my custom markets.json file to limit the serum-vial to listen to only a subset of markets, however this option seems to be not working.

The command I use: npx serum-vial --endpoint <my_rpc_endpoint> --markets-json <absolute_path_to_my_json_file>

The json file contains:
[
  {
    "address": "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT",
    "deprecated": false,
    "name": "SOL/USDC",
    "programId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
  }
]

**Comment by thaaddeus** [comment]
try relative path?

**Comment by yuduan0220** [comment]
Thank you, relative path works fine, that's strange, why absolute path didn't work?
