### ISSUE TITLE
BNB/USDC Spot Market deprecated

### ISSUE THREAD

**Issue by Triggsy22** [tardis-dev/serum-vial#51]
Since nearly two weeks the BNB/USDC Spotmarket in https://api.serum-vial.dev/v1/markets is deprecated now.
The new one has the address: [4UPUurKveNEJgBqJzqHPyi8DhedvpYsMXi7d43CjAg2f](https://explorer.solana.com/address/4UPUurKveNEJgBqJzqHPyi8DhedvpYsMXi7d43CjAg2f)

**Comment by thaaddeus** [comment]
you can always run it on your own with custom markets
