### ISSUE TITLE
Which commitment level does the hosted server use?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [tardis-dev/serum-vial#52]
This is a great project, it's very important for my trading. I use the publicly hosted server but I have a question please:

Do you wait for Finalized slots? Because otherwise it can be sending trades that end up being reversed after a chain fork.

**Comment by thaaddeus** [comment]
It's using 'confirmed' level.

**Comment by SpaceMonkeyForever** [comment]
@thaaddeus thank you for reply!
